---
- hosts: rt
  sudo: yes

  handlers:
    - include: roles/rt/handlers/main.yml
  
  tasks:
    - name: Include database variables
      include_vars: roles/deimosfr.mariadb/defaults/main.yml
    
    - name: Download RT::Extension::ResetPassword
      get_url:
        url: https://cpan.metacpan.org/authors/id/A/AL/ALEXMV/RT-Extension-ResetPassword-1.03.tar.gz
        dest: /tmp/RT-Extension-ResetPassword-1.03.tar.gz
        validate_certs: yes
        sha256sum: a2bd6c9b298ce24d6c43edafe98ec0cbe7d4cfb4d73fbc6fd3fac37e4cefcd03
        force: no

    - name: Untar and ungzip RT::Extension::ResetPassword
      unarchive:
        copy: no
        src: /tmp/RT-Extension-ResetPassword-1.03.tar.gz
        dest: /tmp
        creates: RT-Extension-ResetPassword-1.03

    - name: Make RT::Extension::ResetPassword Makefile
      command: perl Makefile.PL
      args:
        chdir: /tmp/RT-Extension-ResetPassword-1.03
        creates: /tmp/RT-Extension-ResetPassword-1.03/Makefile

    - name: Make RT::Extension::ResetPassword
      command: make
      args:
        chdir: /tmp/RT-Extension-ResetPassword-1.03
        creates: /tmp/RT-Extension-ResetPassword-1.03/blib/lib/RT/Extension/ResetPassword.pm

    - name: Install RT::Extension::ResetPassword
      command: make install
      args:
        chdir: /tmp/RT-Extension-ResetPassword-1.03

    - name: Initialize RT::Extension::ResetPassword database
      shell: echo {{ mariadb_root_password }} | make initdb
      args:
        chdir: /tmp/RT-Extension-ResetPassword-1.03

    - name: Enable RT::Extension::ResetPassword in RT_SiteConfig.pm
      lineinfile:
        dest: /opt/rt4/etc/RT_SiteConfig.pm
        line: Plugin('RT::Extension::ResetPassword');
        state: present
        insertbefore: 1;
      notify: Clear Mason cache
