---

- name: Download RT extension tarball
  get_url:
    url: "{{ ext.url_base }}/{{ ext.name }}-{{ ext.version }}.tar.gz"
    dest: /tmp/{{ ext.name }}-{{ ext.version }}.tar.gz
    validate_certs: yes
    sha256sum: "{{ ext.checksum }}"
    force: no

- name: Untar and ungzip RT extension tarball
  unarchive:
    copy: no
    src: /tmp/{{ ext.name }}-{{ ext.version }}.tar.gz
    dest: /tmp
    creates: /tmp/{{ ext.name }}-{{ ext.version }}

- name: Generate RT extension Makefile
  command: perl Makefile.PL
  args:
    chdir: /tmp/{{ ext.name }}-{{ ext.version }}
    creates: /tmp/{{ ext.name }}-{{ ext.version }}/Makefile

- name: Build RT extension
  command: make
  args:
    chdir: /tmp/{{ ext.name }}-{{ ext.version }}
    #creates: /tmp/{{ ext.name }}-{{ ext.version }}/blib/lib/RT/Extension/ResetPassword.pm
  
- name: Install RT extension
  command: make install
  args:
    chdir: /tmp/{{ ext.name }}-{{ ext.version }}

- name: Initialize RT extension database
  shell: echo {{ mariadb_root_password }} | make initdb
  args:
    chdir: /tmp/{{ ext.name }}-{{ ext.version }}

- name: Enable RT extension in RT_SiteConfig.pm
  lineinfile:
    dest: /opt/rt4/etc/RT_SiteConfig.pm
    line: Plugin('{{ ext.perl_pkg }}');
    state: present
    insertbefore: 1;
  notify: Clear Mason cache
