---

- include: perl-dependencies.yml

- name: Create CPAN config directory
  command: mkdir --parents /root/.cpan/CPAN --mode=0755

- name: Configure CPAN
  copy:
    src: roles/rt/files/MyConfig.pm
    dest: /root/.cpan/CPAN/MyConfig.pm
    owner: root
    group: root
    mode: 0644

- name: Test rt4 database presence
  shell: /usr/bin/mysql --user=root --password={{ mariadb_root_password }} --batch --execute='show databases;' | grep --quiet rt4
  register: db_test
  failed_when: False
  changed_when: False
  
- include: install_rt.yml
  when: db_test|failed
  
- name: Install RT_SiteConfig.pm
  copy:
    src: roles/rt/files/RT_SiteConfig.pm
    dest: /opt/rt4/etc/RT_SiteConfig.pm
    owner: root
    group: www-data
    mode: 0440
  notify: Restart Apache

- include: apache.yml

- include: install-extension.yml
  vars:
    ext: "{{ extensions.ResetPassword }}"
