---

- include: perl-dependencies.yml

- name: Create CPAN config directory
  command: mkdir --parents /root/.cpan/CPAN --mode=0755

- name: Configure CPAN
  copy:
    src: roles/rt/files/MyConfig.pm
    dest: /root/.cpan/CPAN/MyConfig.pm
    owner: root
    group: root
    mode: 0644
    
- name: Download RT 4.2.12
  get_url:
    url: https://github.com/bestpractical/rt/archive/rt-4.2.12.zip
    dest: /tmp/rt-4.2.12.zip
    validate_certs: yes
    sha256sum: 5b69420cd10b723414ebad862da3286fc0077a5ca0ac54b3694fc257040fb498
    force: no

- name: Unzip RT
  unarchive:
    copy: no
    src: /tmp/rt-4.2.12.zip
    dest: /tmp
    creates: /tmp/rt-rt-4.2.12

- name: Build RT configure script
  shell: ./configure.ac
  args:
    chdir: /tmp/rt-rt-4.2.12
    creates: /tmp/rt-rt-4.2.12/configure

- name: Configure RT
  shell: ./configure
  args:
    chdir: /tmp/rt-rt-4.2.12
    ## Creates this file, among many others. Should all be listed?
    creates: /tmp/rt-rt-4.2.12/etc/RT_config.pm

## TODO: Test RT dependencies with 'make testdeps'

- name: Fix RT dependencies
  command: make fixdeps
  args:
    chdir: /tmp/rt-rt-4.2.12

- name: Install RT
  command: make install
  args:
    chdir: /tmp/rt-rt-4.2.12

- name: Initialize RT database
  shell: echo "root" | make initialize-database
  args:
    chdir: /tmp/rt-rt-4.2.12

- include: apache.yml
