---
- name: Install Apache
  yum:
    name: httpd
    state: present
  notify: Sync yum cache

- name: Enable Apache
  service:
    name: httpd
    enabled: yes
    
- name: Install FastCGI module for Apache
  yum:
    name: mod_fcgid
    state: present
  notify: Sync yum cache

# Increase mod_fcgid request size to handle attachments in RT
# https://www.bestpractical.com/docs/rt/4.2.12/web_deployment.html
- name: Configure mod_fcgid
  lineinfile:
    dest: /etc/httpd/conf.d/fcgid.conf
    line: FcgidMaxRequestLen 1073741824
    state: present

- name: Configure Apache RT site
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    owner: root
    group: root
    mode: 0644
    backup: yes
    
#- include: mysql.yml

#- name: Test rt4 database presence
#  shell: /usr/bin/mysql --user=root --password={{ mysql_root_password }} --batch --execute='show databases;' | grep --quiet rt4
#  register: db_test
#  failed_when: False
#  changed_when: False
#  
#- include: install_rt.yml
#  when: db_test|failed

#
#- include: install_rt_ext.yml
#  vars:
#    ext: "{{ extensions.ResetPassword }}"
