---
- name: Create CPAN config directory
  file:
    path: /root/.cpan/CPAN
    state: directory
    recurse: no
    owner: root
    group: root
    mode: 0755
  
- name: Copy CPAN config file
  copy:
    src: MyConfig.pm
    dest: /root/.cpan/CPAN/MyConfig.pm
    owner: root
    group: root
    mode: 0644
