---

- name: no keepcache=0
  lineinfile:
    dest: /etc/yum.conf
    line: keepcache=0
    state: absent
  
- name: keepcache=1
  lineinfile:
    dest: /etc/yum.conf
    line: keepcache=1
    state: present
  
- name: Install CentOS Development tools
  yum:
    name: "@Development tools"
    state: installed
  notify: Sync yum cache

- name: Install Perl 5.10.1
  include: perl_5.10.1.yml
  
- name: Install RT
  include: rt.yml
  
#- name: Install Apache
#  apt:
#    name: apache2
#    state: present
#
#- name: Install FastCGI module for Apache
#  apt:
#    name: libapache2-mod-fcgid
#    state: present
#
#- name: Configure mod_fcgid
#  lineinfile:
#    dest: /etc/apache2/mods-available/fcgid.conf
#    line: "  FcgidMaxRequestLen 1073741824"
#    insertafter: "  FcgidConnectTimeout 20"
#    state: present
#
#- include: mysql.yml
#
#- name: Install build-essential
#  apt:
#    name: build-essential
#    state: present

#- include: centos/perl_5.10.1_rt_deps.yml
#  when: ansible_distribution == 'CentOS'

#- name: Test rt4 database presence
#  shell: /usr/bin/mysql --user=root --password={{ mysql_root_password }} --batch --execute='show databases;' | grep --quiet rt4
#  register: db_test
#  failed_when: False
#  changed_when: False
#  
#- include: install_rt.yml
#  when: db_test|failed

#- name: Configure Apache RT site
#  copy:
#    src: 001-rt.conf
#    dest: /etc/apache2/sites-available/001-rt.conf
#    owner: root
#    group: root
#    mode: 0644
#
#- name: Disable default Apache site
#  file:
#    path: /etc/apache2/sites-enabled/000-default.conf
#    state: absent
#
#- name: Enable Apache RT site
#  file:
#    path: /etc/apache2/sites-enabled/001-rt.conf
#    state: link
#    src: /etc/apache2/sites-available/001-rt.conf
#  notify: Restart Apache
#
#- include: install_rt_ext.yml
#  vars:
#    ext: "{{ extensions.ResetPassword }}"
