---
# Fix man and perldoc escape sequence processing
- name: Push pager.sh
  template:
    src: pager.sh
    dest: /etc/profile.d/pager.sh

- name: Install policycoreutils-python
  yum:
    name: policycoreutils-python
    state: installed

- include: local_facts.yml

- name: Setup SELinux for RT
  include: selinux.yml
  when: selinux
  
- name: keepcache=1
  replace: 
    dest: /etc/yum.conf
    regexp: ^keepcache=0$
    replace: keepcache=1

- name: Install CentOS Development tools
  yum:
    name: "@Development tools"
    state: installed

- name: Setup TLS
  include: tls.yml

- name: Install Apache
  include: apache.yml

- name: Install MariaDB
  include: mysql.yml

- name: Install RT dependencies
  include: rt_deps.yml
  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"

- name: Install RT
  include: rt.yml
  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"

- name: Install RT extensions
  include: install_extensions.yml
