---
- name: keepcache=1
  replace:
    dest: /etc/yum.conf
    regexp: ^keepcache=0$
    replace: keepcache=1

- name: Install CentOS Development tools
  yum:
    name: "@Development tools"
    state: installed
  notify: Sync yum cache

- name: Install Perl 5.10.1
  include: perl_5.10.1.yml

- name: Install RT
  include: rt.yml
