---
#- fail:
#    msg: RT downgrade is not supported
#  when: item.0|int < item.1|int
#  with_together:
#    - "{{ rt_version.split('.') }}"
#    - "{{ ansible_local.rt_versions['RT'].split('.') }}"


# Don't run default tasks in refresh mode
- set_fact:
    defaults: no
  when: refresh_rt or refresh_database

- block:
  - name: Base RT system configuration
    include: base/main.yml

  - block:
    - set_fact:
        upgrade: yes
      when: version_part.0|int > version_part.1|int
      with_together:
        - "{{ rt_version.split('.') }}"
        - "{{ ansible_local.rt_versions.RT.split('.') }}"
      loop_control:
        loop_var: version_part
    when: ansible_local.rt_versions.RT

  - name: Install or upgrade RT
    include: rt/main.yml

  - name: Install RT extensions
    include: rt_extensions/main.yml
    with_items: "{{ rt_extensions }}"
    loop_control:
      loop_var: rt_extension

  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"

  when: defaults

- name: Refresh RT
  include: refresh/main.yml
  environment:
    PERLBREW_ROOT: "{{ perlbrew_root }}"
  when: refresh_rt or refresh_database
