---
# Fail when either of the mutually exclusive sets of variables are true.
- fail:
    msg: "{{ usage }}"
  when: ( fixdeps or install or initialize_db ) and ( refresh_rt or refresh_db )

# Don't run all defaults when any of the variables for individual
# default actions are true.
- set_fact:
    all_defaults: no
  when: fixdeps or install or initialize_db

# Don't run any defaults when any of the variables for meta actions
# are true.
- set_fact:
    defaults: no
    all_defaults: no
  when: refresh_rt or refresh_db

- block:
  - set_fact:
      all_defaults: no
    when: fixdeps or install or initialize_db
    
  - include: fixdeps/main.yml      
    tags:
      - fixdeps
    when: all_defaults or fixdeps

  - name: Install RT
    include: rt.yml
    environment:
      PERLBREW_ROOT: "{{ perlbrew_root }}"
    when: all_defaults or install

  - name: Initialize RT database
    include: rt_db.yml
    when: all_defaults or initialize_db

  - name: Install RT extensions
    include: install_extensions.yml
    when: all_defaults or install

  when: defaults

- debug:
    msg: Refresh RT
  when: refresh_rt

- debug:
    msg: Refresh RT database
  when: refresh_db
