---
- name: Install policycoreutils-python
  yum:
    name: policycoreutils-python
    state: installed

- include: local_facts.yml

- name: Setup SELinux for RT
  include: selinux.yml
  when: selinux

- name: Install CentOS Development tools
  yum:
    name: "@Development tools"
    state: installed

- name: Install Apache
  include: apache.yml

- name: Install RT
  include: rt.yml
  tags:
    - install_rt
