---
- name: Install MariaDB server
  apt:
    name: mariadb-server
    state: present

- name: Install MariaDB client
  apt:
    name: mariadb-client
    state: present

- name: Install PythonMySQLDB
  apt:
    name: python-mysqldb
    state: present

- name: Set MySQL root password
  mysql_user:
    login_user: root
    login_password: ""
    name: root
    password: "{{ mysql_root_password }}"
