---
## mysql_root_password must not contain special chars
## TODO: fix that.
- name: Install MariaDB server
  shell: |
    export DEBIAN_FRONTEND="noninteractive"
    debconf-set-selections <<< "mariadb-server mysql-server/root_password password {{ mysql_root_password }}"
    debconf-set-selections <<< "mariadb-server mysql-server/root_password_again password {{ mysql_root_password }}"
    aptitude install -y mariadb-server
  args:
      executable: /bin/bash

## Following tasks taken from mysql_secure_installation
- name: Delete anonymous MariaDB users
  command: mysql --user=root --password={{ mysql_root_password }} -e "DELETE FROM mysql.user WHERE User='';"

- name: Disallow remote root MariaDB login
  command: mysql --user=root --password={{ mysql_root_password }} -e "DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1');"

- name: Reload privilege table
  command: mysql --user=root --password={{ mysql_root_password }} -e "FLUSH PRIVILEGES;"
