---
- include_vars: perlbrew_rpm_deps.yml
- name: Install CPAN deps for perlbrew from yum
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ perlbrew_rpm_deps }}"
  notify: Pull /var/cache/yum

# Missed Pod::Usage dependency
# perlbrew will fail to install Pod::Usage >= 1.64
# Installing Pod::Find installs correct Pod::Usage version
- name: Install Pod::Find
  become: no
  cpanm:
    name: "Pod::Find"
    system_lib: yes
  notify: Pull /usr/local

- name: Install perlbrew
  become: no
  cpanm:
    name: "App::perlbrew"
    system_lib: yes
  notify: Pull /usr/local

- name: Set PERLBREW_ROOT
  lineinfile:
    dest: /etc/environment
    line: PERLBREW_ROOT=/opt/perl5
    state: present

- name: Init perlbrew
  command: /usr/local/bin/perlbrew init
  changed_when: False

- name: Install perlbrew cpanm
  command: /usr/local/bin/perlbrew install-cpanm
  args:
    creates: /opt/perl5/bin/cpanm
  notify: Pull /opt/perl5

- name: List perl installations
  command: /usr/local/bin/perlbrew list
  register: perlbrew_list_result
  changed_when: False

- name: Install perl 5.10.1
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  shell: |
    source ${PERLBREW_ROOT}/etc/bashrc
    /usr/local/bin/perlbrew install 5.10.1
  notify: Pull /opt/perl5
  when: "'perl-5.10.1' not in perlbrew_list_result.stdout"

- name: Source perlbrew bashrc in login shells
  lineinfile:
    dest: /etc/profile
    line: source ${PERLBREW_ROOT}/etc/bashrc
    state: present

- name: Switch to perl 5.10.1 in login shells
  lineinfile:
    dest: /etc/profile
    line: perlbrew switch 5.10.1
    state: present
