---
- name: Find perlbrew
  command: which perlbrew
  register: which_perlbrew
  changed_when: false
  failed_when: false

- include_vars: perlbrew_rpm_deps.yml
  
- block:

    - name: Install CPAN deps for perlbrew from yum
      yum:
        name: "{{ item }}"
        state: latest
      with_items: "{{ perlbrew_rpm_deps }}"

      # Missed Pod::Usage dependency
      # perlbrew will fail to install Pod::Usage >= 1.64
      # Installing Pod::Find installs correct Pod::Usage version
    - name: Install Pod::Find
      become: no
      cpanm:
        name: "Pod::Find"
        system_lib: yes
        notest: "{{ cpanm_notest }}"

    - name: Install perlbrew
      become: no
      cpanm:
        name: "App::perlbrew"
        system_lib: yes
        notest: "{{ cpanm_notest }}"

    - name: Init perlbrew
      environment:
        PERLBREW_ROOT: /opt/perl5
      command: /usr/local/bin/perlbrew init
      changed_when: False

    - name: Install perlbrew cpanm
      environment:
        PERLBREW_ROOT: /opt/perl5
      command: /usr/local/bin/perlbrew install-cpanm -j {{ ansible_processor_vcpus + 1 }}
      args:
        creates: /opt/perl5/bin/cpanm

  when: which_perlbrew|failed

- name: List perl installations
  environment:
    PERLBREW_ROOT: /opt/perl5
  command: /usr/local/bin/perlbrew list
  register: perlbrew_list
  changed_when: False
  failed_when: False

  # If no perlbrew_notest is true, --notest. Else, empty string.
- name: Install preferred perl version
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5
  command: >-
    /usr/local/bin/perlbrew install
    -j {{ ansible_processor_vcpus + 1 }}
    {{ perlbrew_notest | ternary('--notest','') }}
    {{ perl_version }}
  when: "'{{ perl_version }}' not in perlbrew_list.stdout"

- name: Push perlbrew.sh
  template:
    src: perlbrew.sh
    dest: /etc/profile.d/perlbrew.sh
