---
- name: Install CPAN deps for perlbrew
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ perlbrew_rpm_deps }}"
  notify: Sync yum cache

# Missed Pod::Usage dependency
# perlbrew will fail to install Pod::Usage >= 1.64
# Installing Pod::Find installs correct Pod::Usage version
- name: Install Pod::Find
  become: no
  cpanm:
    name: "Pod::Find"
    system_lib: yes
  notify: Sync cpanm

- name: Install perlbrew
  become: no
  cpanm:
    name: "App::perlbrew"
    system_lib: yes
  notify: Sync cpanm

- name: Set PERLBREW_ROOT
  lineinfile:
    dest: /etc/environment
    line: PERLBREW_ROOT=/opt/perl5
    state: present

- name: Init perlbrew
  command: /usr/local/bin/perlbrew init
  changed_when: False

- name: Install perlbrew cpanm
  command: /usr/local/bin/perlbrew install-cpanm
  args:
    creates: /opt/perl5/bin/cpanm
  notify: Sync /opt/perl5

- name: List perl installations
  command: /usr/local/bin/perlbrew list
  register: perlbrew_list_result
  changed_when: False

- name: Install perl 5.10.1
  command: /usr/local/bin/perlbrew install 5.10.1
  notify: Sync /opt/perl5
  when: "'perl-5.10.1' not in perlbrew_list_result.stdout"

### TODO: Verify local perlbrew cache containing perl 5.10.1 and CPAN deps for RT
### TODO: Install cache under perlbrew_root to PERLBREW_ROOT on host
##- name: Sync cached perl 5.10.1 packages to RT host
##  local_action: stat path=roles/bcduggan.rt/files/centos/MANIFEST_perlbrew_root
##  sudo: no
##  register: cache_presence
##
##- debug:
##    var: cache_presence
##  
##- name: Sync cached perl 5.10.1 and CPAN deps for RT to host
##  synchronize:
##    src: ../../files/centos/perlbrew_root/
##    dest: /opt/perl5
##    owner: no
##    group: no
##    checksum: yes
##    rsync_path: "sudo rsync"
##  register: perl_sync_result
##  ignore_errors: True
##    
##- debug:
##    var: perl_sync_result
#    

