---
# This merits a lot of explanation...      
- name: Install packages with perlbrew cpanm
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  shell: |
    source ${PERLBREW_ROOT}/etc/bashrc
    perlbrew use 5.10.1
    cpanm {{ item }}
  notify: Sync /opt/perl5
  register: perlbrew_cpanm_result
  changed_when: >
    perlbrew_cpanm_result|success and
    perlbrew_cpanm_result.stdout_lines|length > 1
  with_items: packages
