---
- include_vars: perlbrew_rpm_deps.yml
- name: Install CPAN deps for perlbrew from yum
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ perlbrew_rpm_deps }}"
  notify: Pull /var/cache/yum

# Missed Pod::Usage dependency
# perlbrew will fail to install Pod::Usage >= 1.64
# Installing Pod::Find installs correct Pod::Usage version
- name: Install Pod::Find
  become: no
  cpanm:
    name: "Pod::Find"
    system_lib: yes
  notify: Pull /usr/local

- name: Install perlbrew
  become: no
  cpanm:
    name: "App::perlbrew"
    system_lib: yes
  notify: Pull /usr/local

- name: Push perlbrew.sh
  template:
    src: perlbrew.sh
    dest: /etc/profile.d/perlbrew.sh

- name: Init perlbrew
  environment:
    PERLBREW_ROOT: /opt/perl5
  command: /usr/local/bin/perlbrew init
  changed_when: False

- name: Install perlbrew cpanm
  environment:
    PERLBREW_ROOT: /opt/perl5
  command: /usr/local/bin/perlbrew install-cpanm
  args:
    creates: /opt/perl5/bin/cpanm
  notify: Pull /opt/perl5

- name: List perl installations
  environment:
    PERLBREW_ROOT: /opt/perl5
  command: /usr/local/bin/perlbrew list
  register: perlbrew_list_result
  changed_when: False

#    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
#source ${PERLBREW_ROOT}/etc/bashrc
- name: Install preferred perl version
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5
  command: /usr/local/bin/perlbrew install {{ perl_version }}
  notify: Pull /opt/perl5
  when: "'perl-5.10.1' not in perlbrew_list_result.stdout"

