---
- include_vars: rt_cpan_deps.yml

# This merits a lot of explanation...      
- name: Install RT deps from perlbrew cpanm
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  shell: |
    source ${PERLBREW_ROOT}/etc/bashrc
    perlbrew use 5.10.1
    cpanm {{ item.1 }}
  notify: Sync /opt/perl5
  register: perlbrew_cpanm_result
  changed_when: >
    perlbrew_cpanm_result|success and
    perlbrew_cpanm_result.stdout_lines|length > 1
  with_subelements:
    - rt_cpan_deps
    - packages

#- name: Install Mojolicious 5.17
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo JHTHORSEN/Mojolicious-5.17.tar.gz
#  args:
#    creates: /opt/perl5/perls/perl-5.10.1/lib/site_perl/5.10.1/Mojolicious.pm
#  notify: Sync /opt/perl5

## Allows cpanm to keep state.. or something?
#- name: Install perl YAML
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo YAML
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
#
#- name: Install RT CLI deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_cli_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT CORE deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_core_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT DASHBOARDS deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_dashboards_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT DEVELOPER deps with --force
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo --force {{ item }}
#  with_items: "{{ rt_developer_cpan_force_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#  
#- name: Install RT DEVELOPER deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_developer_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT FASTCGI deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_fastcgi_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT GD deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_gd_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT GPG deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_gpg_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT GRAPHVIZ deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_graphviz_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT HTML-DOC deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_htmldoc_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT ICAL deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_ical_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT MAILGATE deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_mailgate_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT MYSQL deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_mysql_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT SMIME deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_smime_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False
#
#- name: Install RT USERLOGO deps
#  become: no
#  shell: |
#    source ${PERLBREW_ROOT}/etc/bashrc
#    perlbrew switch 5.10.1
#    cpanm --sudo {{ item }}
#  with_items: "{{ rt_userlogo_cpan_deps }}"
#  notify:
#    - Sync cpanm cache
#    - Sync /opt/perl5
##  changed_when: False

