---
# Need dest_port because 'vagrant provision' will impose its default, otherwise.
- name: Push /var/cache/yum
  become: no
  synchronize:
    src: cache/{{ ansible_hostname }}/var.cache.yum/
    dest: /var/cache/yum
    dest_port: 22
    rsync_path: "sudo rsync"

- name: Push /usr/local
  become: no
  synchronize:
    src: cache/{{ ansible_hostname }}/usr.local/
    dest: /usr/local
    dest_port: 22
    rsync_path: "sudo rsync"

- name: Push /opt/perl5
  become: no
  synchronize:
    src: cache/{{ ansible_hostname }}/opt.perl5/
    dest: /opt/perl5
    dest_port: 22
    rsync_path: "sudo rsync"
