---
- name: Install RPM deps for RT
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - openssl-devel
    - graphviz-devel
    - libxml2-devel
    - expat-devel
    - gd-devel
    - mariadb-devel

- name: Create /opt/src
  file:
    mode: 0755
    path: /opt/src
    state: directory

- name: Include Supported Version information
  include_vars: rt_versions.yml

- name: Download RT
  get_url:
    url: https://download.bestpractical.com/pub/rt/release/{{ rt_version }}.tar.gz
    dest: /opt/src/{{ rt_version }}.tar.gz
    validate_certs: yes
    sha256sum: "{{ rt[rt_version].checksum }}"
    force: no

- name: Untar and ungzip RT
  unarchive:
    copy: no
    src: /opt/src/{{ rt_version }}.tar.gz
    dest: /opt/src
    creates: /opt/src/{{ rt_version }}
    owner: root
    group: root

- name: Configure RT
  shell: |
    ./configure \
    --enable-developer \
    --enable-graphviz \
    --enable-gd
    --enable-gpg \
    --enable-smime
  args:
    chdir: /opt/src/{{ rt_version }}
    creates: /opt/src/{{ rt_version }}/config.status

- name: Test RT dependencies
  shell: |
    make testdeps
  args:
    chdir: /opt/src/{{ rt_version }}
  register: rt_testdeps
  changed_when: False
  failed_when: False

- name: Include information about cpan packages for pinning versions (?)
  include_vars: pinned_cpan_packages.yml

- block:
    - name: Install pinned CPAN packages
      shell: |
        cpanm {{ cpanm_notest | ternary('--notest','--no-notest') }} {{ item }}
      register: perlbrew_cpanm_result
      changed_when: >
        perlbrew_cpanm_result|success and
        perlbrew_cpanm_result.stdout_lines|length > 1
      with_items: "{{ perl_5_10_1 }}"

    - name: Fix RT dependencies
      environment:
        RT_FIX_DEPS_CMD: /opt/perl5/bin/cpanm
        PERL_CPANM_OPT: "{{ cpanm_notest | ternary('--notest','--no-notest') }}"
      shell: |
        make -j {{ ansible_processor_vcpus + 1 }} fixdeps
      args:
        chdir: /opt/src/{{ rt_version }}

  when: rt_testdeps|failed

  # Several extensions depend on this module, which make fixdeps does
  # not install
- name: "Install DateTime::Set"
  shell: |
    cpanm {{ cpanm_notest | ternary('--notest','--no-notest') }} DateTime::Set
  register: datetime_set_result
  changed_when: >
    datetime_set_result|success and
    datetime_set_result.stdout_lines|length > 1

- name: Install RT
  shell: |
    make install
  args:
    chdir: /opt/src/{{ rt_version }}
    creates: /opt/rt5

- debug:
    msg: "TODO: Assemble RT_SiteConfig.pm from parts to avoid clobbering local changes"

- name: Install RT_SiteConfig.pm
  template:
    src: RT_SiteConfig.pm
    dest: /opt/rt5/etc/RT_SiteConfig.pm
    mode: 0640
    backup: yes
  notify: Restart Apache

- name: Set Mason cache owner
  set_fact:
    cache_owner: "{{ selinux | ternary('root','apache') }}"

- name: Set RT Mason cache attributes
  file:
    path: /opt/rt5/var/mason_data
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: 0750

- name: Create GnuPG home directory
  file:
    path: /opt/rt5/var/data/gpg
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: 0750

- name: Create S/MIME home directory
  file:
    path: /opt/rt5/var/data/smime
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: 0750

- name: Push rt.sh
  template:
    src: rt.sh
    dest: /etc/profile.d/rt.sh
    mode: 0644
