---
- name: Install RT
  command: >
    {{ perlbrew }} exec --with perl-5.10.1
    'make install'
  args:
    chdir: "{{ rt_src_dir }}"
    creates: "{{ rt_dir }}"

- name: Install RT_SiteConfig.pm
  template:
    src: RT_SiteConfig.pm
    dest: "{{ rt_dir }}/etc/RT_SiteConfig.pm"
    backup: yes
  notify: Restart Apache

- name: Set Mason cache owner
  set_fact:
    cache_owner: "{{ selinux | ternary('root','apache') }}"

- name: Set RT Mason cache attributes
  file:
    path: "{{ rt_dir }}/var/mason_data"
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: o+rx

- name: Create GnuPG home directory
  file:
    path: "{{ rt_dir }}/var/data/gpg"
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"

- name: Create S/MIME home directory
  file:
    path: "{{ rt_dir }}/var/data/smime"
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"

- name: Push rt4.sh
  template:
    src: rt4.sh
    dest: /etc/profile.d/rt4.sh
