---
- name: Download RT
  get_url:
    url: https://download.bestpractical.com/pub/rt/release/{{ rt_version }}.tar.gz
    dest: /opt/src/{{ rt_version }}.tar.gz
    validate_certs: yes
    sha256sum: "{{ rt[rt_version].checksum }}"
    force: no

- name: Untar and ungzip RT
  unarchive:
    copy: no
    src: /opt/src/{{ rt_version }}.tar.gz
    dest: /opt/src
    creates: /opt/src/{{ rt_version }}

- name: Configure RT
  shell: >
    ./configure
    --enable-developer
    --enable-graphviz
    --enable-gd
    --enable-gpg
    --enable-smime
  args:
    chdir: /opt/src/{{ rt_version }}
    ## Creates this file, among many others. Should all be listed?
    creates: /opt/src/{{ rt_version }}/etc/RT_config.pm
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5

- name: Test RT dependencies
  command: make testdeps
  args:
    chdir: /opt/src/{{ rt_version }}
  register: testdeps
  failed_when: False
  changed_when: False
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5
    
- name: Fix RT dependencies
  command: make fixdeps
  args:
    chdir: /opt/src/{{ rt_version }}
  when: testdeps|failed
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5

- name: Install RT
  command: make install
  args:
    chdir: /tmp/{{ rt_version }}
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
    PERLBREW_ROOT: /opt/perl5

- name: Initialize RT database
  shell: echo {{ mysql_root_password }} | make initialize-database
  args:
    chdir: /tmp/{{ rt_version }}

- name: Install RT_SiteConfig.pm
  copy:
    src: RT_SiteConfig.pm
    dest: /opt/rt4/etc/RT_SiteConfig.pm
    owner: root
    group: www-data
    mode: 0440
  notify: Restart Apache
