---
- name: Test rt4 database presence
  command: >
    /bin/mysql --user=root --password={{ mysql_root_password }}
    --batch --execute='show databases;'
  register: rt4_db_test
  changed_when: False

- name: Initialize RT database
  command: >
    {{ perlbrew }} exec --with perl-5.10.1
    'echo {{ mysql_root_password }} | make initialize-database'
  args:
    chdir: "{{ rt_src_dir }}"
  when: '"rt4" not in rt4_db_test.stdout_lines'
