---
- name: Restart Apache
  service:
    name: httpd
    state: restarted

- name: Clear Mason cache
  file:
    path: /opt/rt4/var/mason_data/obj
    state: absent
  notify: Restart Apache

# HEADSUP for rsync commands: Vagrant hosts typically have
# StrictHostKeyChecking=no somewhere in the vagrant->ansible->rsync->ssh chain.
# If this command results in error due to a nonexistant file, rsync's error output
# will spend most of its characters complaining that the remote host key has
# changed on 'vagrant up'. But the real error is still a nonexistant file.
  
# synchronize in pull mode is broken in Ansible 2?
- name: Sync yum cache
  become: no
  command: >
    /usr/bin/rsync -az
    -e "ssh -p {{ ansible_ssh_port }}
    -i {{ ansible_ssh_private_key_file }}
    -l {{ ansible_ssh_user }}
    -o StrictHostKeyChecking=no"
    {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/var/cache/yum/
    {{ lookup('env','HOME') }}/ansible/vagrant/rt/yum
  delegate_to: localhost
  when: ansible_virtualization_role == "guest"

# synchronize in pull mode is broken in Ansible 2?
- name: Sync cpanm cache
  become: no
  command: >
    /usr/bin/rsync -az
    -e "ssh -p {{ ansible_ssh_port }}
    -i {{ ansible_ssh_private_key_file }}
    -l {{ ansible_ssh_user }}
    -o StrictHostKeyChecking=no"
    {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/home/vagrant/.cpanm/
    {{ lookup('env','HOME') }}/ansible/vagrant/rt/cpanm
  delegate_to: localhost
  when: ansible_virtualization_role == "guest"

# synchronize in pull mode is broken in Ansible 2?
- name: Sync /usr/local
  become: no
  command: >
    /usr/bin/rsync -az
    -e "ssh -p {{ ansible_ssh_port }}
    -i {{ ansible_ssh_private_key_file }}
    -l {{ ansible_ssh_user }}
    -o StrictHostKeyChecking=no"
    {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/usr/local/
    {{ lookup('env','HOME') }}/ansible/vagrant/rt/local
  delegate_to: localhost
  when: ansible_virtualization_role == "guest"

# synchronize in pull mode is broken in Ansible 2?
- name: Sync /opt/perl5
  become: no
  command: >
    /usr/bin/rsync -az
    -e "ssh -p {{ ansible_ssh_port }}
    -i {{ ansible_ssh_private_key_file }}
    -l {{ ansible_ssh_user }}
    -o StrictHostKeyChecking=no"
    {{ ansible_ssh_user }}@{{ ansible_ssh_host }}:/opt/perl5/
    {{ lookup('env','HOME') }}/ansible/vagrant/rt/perl5
  delegate_to: localhost
  when: ansible_virtualization_role == "guest"
  
#- name: Sync cpan
#  synchronize:
#    mode: pull
#    rsync_opts: --exclude='CPAN/MyConfig.pm'
#    src: /root/.cpan/
#    dest: /home/bcduggan/ansible/vagrant/rt/cpan
