---
- name: Restart Apache
  service:
    name: httpd
    state: restarted

- name: Clear Mason cache
  file:
    path: /opt/rt5/var/mason_data/obj
    state: absent
  notify: Restart Apache

- name: reload ansible_local
  setup:
    filter: "ansible_local"
