---
- name: Restart Apache
  service:
    name: apache2
    state: restarted

- name: Clear Mason cache
  file:
    path: /opt/rt4/var/mason_data/obj
    state: absent
  notify: Restart Apache

- name: Sync yum cache
  synchronize:
    mode: pull
    src: /var/cache/yum
    dest: /home/bcduggan/ansible/vagrant/rt/

- name: Sync cpanm
  synchronize:
    mode: pull
    src: /home/vagrant/.cpanm/
    dest: /home/bcduggan/ansible/vagrant/rt/cpanm

#- name: Sync cpan
#  synchronize:
#    mode: pull
#    rsync_opts: --exclude='CPAN/MyConfig.pm'
#    src: /root/.cpan/
#    dest: /home/bcduggan/ansible/vagrant/rt/cpan
