---
- name: Restart Apache
  service:
    name: httpd
    state: restarted

- name: Clear Mason cache
  file:
    path: /opt/rt4/var/mason_data/obj
    state: absent
  notify: Restart Apache

- name: Pull /var/cache/yum
  become: no
  synchronize:
    mode: pull
    src: /var/cache/yum/
    dest: cache/{{ ansible_hostname }}/var.cache.yum
    dest_port: 22
  when: ansible_virtualization_role == "guest"

- name: Pull /usr/local
  become: no
  synchronize:
    mode: pull
    src: /usr/local/
    dest: cache/{{ ansible_hostname }}/usr.local
    dest_port: 22
  when: ansible_virtualization_role == "guest"

- name: Pull /opt/perl5
  become: no
  synchronize:
    mode: pull
    src: /opt/perl5
    dest: cache/{{ ansible_hostname }}/opt.perl5
    dest_port: 22
  when: ansible_virtualization_role == "guest"
