---
- name: Create /etc/ansible/facts.d
  file:
    path: /etc/ansible/facts.d
    state: directory
    owner: root
    group: root
    mode: 0755
    seuser: _default
    serole: _default
    setype: _default
    selevel: _default

- name: Push local fact files and templates
  template:
    src: "{{ fact_file }}"
    dest: /etc/ansible/facts.d/{{ item|basename }}
    owner: root
    group: root
    mode: 0755
    seuser: _default
    serole: _default
    setype: _default
    selevel: _default
  with_fileglob:
    - ../templates/*.fact
  loop_control:
    loop_var: fact_file
  register: push_local_facts_result

- action: setup
  when: push_local_facts_result | changed
