---
- name: Configure RT
  command: >
    {{ perlbrew }} exec --with {{ perl_version }}
    './configure
    --with-db-database={{ rt_db_database }}
    --with-db-host={{ rt_db_host }}
    --with-db-port={{ rt_db_port }}
    --with-db-rt-user={{ rt_db_rt_user }}
    --with-db-rt-pass={{ rt_db_rt_pass }}
    --enable-developer
    --enable-graphviz
    --enable-gd'
#    --enable-gpg
#    --enable-smime
  args:
    chdir: "{{ rt_src_dir }}"
    creates: "{{ rt_src_dir }}/config.status"
