---
- name: Install RT
  environment:
    PERLBREW_ROOT: /opt/perl5
  command: >
    {{ perl_shell }}
    '/usr/bin/make install'
  args:
    chdir: "{{ rt_src_dir }}"
    creates: "{{ rt_dir }}"

- name: Install RT_SiteConfig.pm
  template:
    src: RT_SiteConfig.pm
    dest: "{{ rt_dir }}/etc/RT_SiteConfig.pm"
    backup: yes
  notify: Restart Apache

- name: Set Mason cache owner
  set_fact:
    cache_owner: "{{ selinux | ternary('root','apache') }}"

## There's probably a more concise way to do this.
- name: Set RT Mason cache attributes
  file:
    path: "{{ rt_dir }}/var"
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: o+rx

- name: Set RT Mason cache attributes
  file:
    path: "{{ rt_dir }}/var/log"
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: o+rx

- name: Set RT Mason cache attributes
  file:
    path: "{{ rt_dir }}/var/mason_data"
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
    mode: o+rx

- name: Create GnuPG home directory
  file:
    path: "{{ rt_dir }}/var/data/gpg"
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"

- name: Create S/MIME home directory
  file:
    path: "{{ rt_dir }}/var/data/smime"
    state: directory
    owner: "{{ cache_owner }}"
    group: "{{ cache_owner }}"
